apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cdi.kubevirt.io: cdi-operator
    name: cdi-operator
    operator.cdi.kubevirt.io: ""
    prometheus.cdi.kubevirt.io: "true"
  name: cdi-operator
  namespace: cdi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cdi-operator
      operator.cdi.kubevirt.io: ""
  strategy: {}
  template:
    metadata:
      annotations:
        openshift.io/required-scc: restricted-v2
      labels:
        cdi.kubevirt.io: cdi-operator
        name: cdi-operator
        operator.cdi.kubevirt.io: ""
        prometheus.cdi.kubevirt.io: "true"
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: cdi.kubevirt.io
                  operator: In
                  values:
                  - cdi-operator
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - env:
        - name: DEPLOY_CLUSTER_RESOURCES
          value: "true"
        - name: OPERATOR_VERSION
          value: {{ .Values.cdi.version | quote }}
        - name: CONTROLLER_IMAGE
          value: {{ include "cdi.image" (dict "ctx" . "name" "cdi-controller") | quote }}
        - name: IMPORTER_IMAGE
          value: {{ include "cdi.image" (dict "ctx" . "name" "cdi-importer") | quote }}
        - name: CLONER_IMAGE
          value: {{ include "cdi.image" (dict "ctx" . "name" "cdi-cloner") | quote }}
        - name: OVIRT_POPULATOR_IMAGE
          value: {{ include "cdi.image" (dict "ctx" . "name" "cdi-importer") | quote }}
        - name: APISERVER_IMAGE
          value: {{ include "cdi.image" (dict "ctx" . "name" "cdi-apiserver") | quote }}
        - name: UPLOAD_SERVER_IMAGE
          value: {{ include "cdi.image" (dict "ctx" . "name" "cdi-uploadserver") | quote }}
        - name: UPLOAD_PROXY_IMAGE
          value: {{ include "cdi.image" (dict "ctx" . "name" "cdi-uploadproxy") | quote }}
        - name: VERBOSITY
          value: "1"
        - name: PULL_POLICY
          value: IfNotPresent
        - name: MONITORING_NAMESPACE
        image: {{ include "cdi.image" (dict "ctx" . "name" "cdi-operator") | quote }}
        imagePullPolicy: IfNotPresent
        name: cdi-operator
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 150Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
      serviceAccountName: cdi-operator
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists