{{- if and .Values.hami.enabled .Values.hami.prometheus.serviceMonitor.enabled }}
{{- $crdExists := (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") }}
{{- if $crdExists }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "chart.fullname" . }}-hami-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    {{- with .Values.hami.prometheus.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - honorLabels: true
    port: monitorport
    path: /metrics
    interval: {{ .Values.hami.prometheus.serviceMonitor.interval | default "15s" }}
    scrapeTimeout: {{ .Values.hami.prometheus.serviceMonitor.scrapeTimeout | default "15s" }}
  - honorLabels: true
    port: monitor
    path: /metrics
    interval: {{ .Values.hami.prometheus.serviceMonitor.interval | default "15s" }}
    scrapeTimeout: {{ .Values.hami.prometheus.serviceMonitor.scrapeTimeout | default "15s" }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- else }}
{{- fail "ServiceMonitor CRD is not available in the cluster. Please install Prometheus Operator first." }}
{{- end }}
{{- end }}
