## NVIDIA GPU Operator chart
gpu-operator:
  enabled: true
#  prometheus:
#    podMonitor:
#      enabled: true
#      interval: "15s"
#      scrapeTimeout: "15s"
#      labels:
#        prometheus: monitor        
  driver:
    enabled: true
    version: "570.148.08"
    ## kernelModuleType
    #auto: Default and recommended option.
    #open: Use the NVIDIA Open GPU kernel module driver.
    #proprietary: Use the NVIDIA Proprietary GPU kernel module driver.
    kernelModuleType: "auto"
    upgradePolicy:
      autoUpgrade: false
  toolkit:
    enabled: true
  sandboxWorkloads:
    enabled: true
  devicePlugin:
    enabled: false
  dcgmExporter:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        prometheus: monitor        
    env:
      - name: DCGM_EXPORTER_LISTEN
        value: ":9400"
      - name: DCGM_EXPORTER_KUBERNETES
        value: "true"
      - name: DCGM_EXPORTER_COLLECTORS
        value: "/etc/dcgm-exporter/dcp-metrics-included.csv"
      - name: DCGM_EXPORTER_ENABLE_DCGM_LOG
        value: "false"
      - name: DCGM_EXPORTER_DCGM_LOG_LEVEL
        value: "INFO"

nvidia_device_plugin:
  enabled: true
  version: v0.17.1

hami:
  enabled: true
  prometheus:
    serviceMonitor:
      enabled: true
      interval: "15s"
      scrapeTimeout: "15s"
      labels:
        prometheus: monitor
  resourceName: "otterscale.com/vgpu"
  resourceMem: "otterscale.com/vgpumem"
  resourceMemPercentage: "otterscale.com/vgpumem-percentage"
  resourceCores: "otterscale.com/vgpucores"
  resourcePriority: "otterscale.com/priority"
  scheduler:
    nodeLabelSelector:
      nvidia.com/gpu.workload.config: "vgpu"
    service:
      type: ClusterIP
  devicePlugin:
    runtimeClassName: "nvidia"
    service:
      type: ClusterIP
    nodeSelector:
      nvidia.com/gpu.workload.config: "vgpu"
