apiVersion: v2
name: otterscale
version: 0.6.0
kubeVersion: ">= 1.30.0"
description: OtterScale
keywords:
  - kubernetes
  - containers
  - virtualization
  - storage
  - gpu-management
  - maas
  - juju
  - ceph
  - aidaptiv-cache

maintainers:
  - name: terry
    email: terrywu25@gmail.com

dependencies:
  - name: gatekeeper
    version: 3.20.1
    condition: gatekeeper.enabled
  - name: kong
    version: 2.52.0
    condition: kong.enabled