{{- if .Values.dockerRegistry.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otterscale.fullname" . }}-docker-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: docker-registry
  {{- with .Values.dockerRegistry.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.dockerRegistry.service.type }}
  ports:
    - port: {{ .Values.dockerRegistry.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.dockerRegistry.service.type "NodePort") .Values.dockerRegistry.service.nodePort }}
      nodePort: {{ .Values.dockerRegistry.service.nodePort }}
      {{- end }}
  selector:
    {{- include "otterscale.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: docker-registry
{{- end }}