{{- if and .Values.istio.enabled .Values.istio.virtualService.otterscale.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "otterscale.fullname" . }}-api
  namespace: istio-system
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  hosts:
    - {{ include "otterscale.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    {{- range .Values.istio.virtualService.otterscale.hosts }}
    - {{ . }}
    {{- end }}
  gateways:
    - {{ $.Values.istio.gateway.name }}
    - mesh
  http:
    - match:
      - uri:
          prefix: /
      route:
        - destination:
            host: {{ include "otterscale.fullname" $ }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ $.Values.otterscale.service.port }}
      timeout: 30s
      retries:
        attempts: 3
        perTryTimeout: 10s
{{- end }}
