apiVersion: v1
kind: Service
metadata:
  name: {{ include "otterscale.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- with .Values.otterscale.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.otterscale.service.type }}
  selector:
    {{- include "otterscale.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: connectrpc
      port: {{ .Values.otterscale.service.port }}
      targetPort: {{ .Values.otterscale.service.targetPort }}
      protocol: TCP
