apiVersion: v1
kind: Service
metadata:
  name: {{ include "otterscale.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  {{- with .Values.otterscaleWeb.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.otterscaleWeb.service.type }}
  selector:
    {{- include "otterscale.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.otterscaleWeb.service.port }}
      targetPort: http
      protocol: TCP
