apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otterscale.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  postgres-db: {{ .Values.postgres.db | b64enc | quote }}
  postgres-user: {{ .Values.postgres.user | b64enc | quote }}
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
  postgres-url: {{ printf "postgresql://%s:%s@%s-postgres:5432/%s" .Values.postgres.user .Values.postgres.password (include "otterscale.fullname" .) .Values.postgres.db | b64enc | quote }}
