apiVersion: v1
kind: Service
metadata:
  name: {{ include "otterscale.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet-like behavior
  selector:
    {{- include "otterscale.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
