apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba-operator-controller-manager
  namespace: samba-operator-system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
      annotations:
        kubectl.kubernetes.io/default-logs-container: manager
        kubectl.kubernetes.io/default-container: manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      containers:
        - command:
            - /manager
          args:
            - --enable-leader-election
            - "--metrics-addr=127.0.0.1:8080"
            - "--enable-leader-election"
          env:
            - name: SAMBA_OP_WORKING_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SAMBA_OP_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SAMBA_OP_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: samba-operator-controller-cfg
          image: quay.io/samba.org/samba-operator:latest
          imagePullPolicy: Always
          name: manager
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 20Mi
        - name: kube-rbac-proxy
          # this is apparently the same code as
          # https://github.com/brancz/kube-rbac-proxy/
          # but build by/for kubebuilder. The brancz repo also has

          # newer releases but v0.8 is the latest at this repo
          # according to skopeo on 2021-11-06.
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
          args:
            - "--secure-listen-address=0.0.0.0:8443"
            - "--upstream=http://127.0.0.1:8080/"
            - "--logtostderr=true"
            - "--v=10"
          ports:
            - containerPort: 8443
              name: https
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert
      terminationGracePeriodSeconds: 10