apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: samba-operator-metrics-reader
rules:
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: samba-operator-proxy-role
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources:
      - tokenreviews
    verbs: ["create"]
  - apiGroups: ["authorization.k8s.io"]
    resources:
      - subjectaccessreviews
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: samba-operator-manager-role
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - endpoints
      - namespaces
      - pods
      - services
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheusrules
      - servicemonitors
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbcommonconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbcommonconfigs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbsecurityconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbsecurityconfigs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbshares
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbshares/finalizers
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbshares/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - get
      - list
      - use
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - samba
    resources:
      - securitycontextconstraints
    verbs:
      - create
      - get
      - list
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smbcommonconfig-editor-role
rules:
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbcommonconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbcommonconfigs/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smbcommonconfig-viewer-role
rules:
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbcommonconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbcommonconfigs/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smbsecurityconfig-editor-role
rules:
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbsecurityconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbsecurityconfigs/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smbsecurityconfig-viewer-role
rules:
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbsecurityconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbsecurityconfigs/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smbshare-editor-role
rules:
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbshares
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbshares/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smbshare-viewer-role
rules:
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbshares
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbshares/status
    verbs:
      - get