apiVersion: v2
appVersion: 2.6.1
description: Heterogeneous AI Computing Virtualization Middleware
keywords:
- vgpu
- gpu
kubeVersion: '>= 1.18.0-0'
maintainers:
- email: archlitchi@gmail.com
  name: limengxuan
- email: xiaozhang0210@hotmail.com
  name: zhangxiao
name: hami
type: application
version: 2.6.1
