{{- if and .Values.istio.enabled .Values.istio.destinationRule.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "otterscale.fullname" . }}
  namespace: istio-system
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
spec:
  host: {{ include "otterscale.fullname" . }}
  trafficPolicy:
    {{- if .Values.istio.destinationRule.connectionPool }}
    connectionPool:
      {{- toYaml .Values.istio.destinationRule.connectionPool | nindent 6 }}
    {{- end }}
    {{- if .Values.istio.destinationRule.outlierDetection }}
    outlierDetection:
      {{- toYaml .Values.istio.destinationRule.outlierDetection | nindent 6 }}
    {{- end }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "otterscale.fullname" . }}-web
  namespace: istio-system
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
spec:
  host: {{ include "otterscale.fullname" . }}-web
  trafficPolicy:
    {{- if .Values.istio.destinationRule.connectionPool }}
    connectionPool:
      {{- toYaml .Values.istio.destinationRule.connectionPool | nindent 6 }}
    {{- end }}
    {{- if .Values.istio.destinationRule.outlierDetection }}
    outlierDetection:
      {{- toYaml .Values.istio.destinationRule.outlierDetection | nindent 6 }}
    {{- end }}
{{- end }}
