{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ include "otterscale.fullname" . }}-postgres-external
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ include "otterscale.fullname" . }}-postgres
  location: MESH_INTERNAL
  ports:
    - number: 5432
      name: tcp-postgres
      protocol: TCP
  resolution: DNS
{{- end }}
